title: Mudasirullah Stanikzai
logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
# Use a sidebar on home page
defaults:
  -
  
      sidebar:
        nav: "_data/navigation.yml"  # points to your sidebar links
