<!-- GLightbox CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.2.0/css/glightbox.min.css" />

<!-- GLightbox JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.2.0/js/glightbox.min.js"></script>

title: Mudasirullah Stanikzai
logo: /assets/img/Profile.jpg
# description: Minimal is a theme for GitHub Pages.
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
